### ISSUE TITLE
Initializing with Swift?

### ISSUE THREAD

**Issue by Razinsky** [arielelkin/PocketSVG#32]
Hi,

I'm trying to initialize PocketSVG in a Swift project but the compiler doesn't seems to recognize the <code>pathFromSVGFileNamed</code> argument. Here's my code and the error I get:
<pre>let myShape: CGPathRef = PocketSVG(pathFromSVGFileNamed: "BezierCurve1");</pre>
<pre>ViewController.swift:25:41: Extra argument 'pathFromSVGFileNamed' in call</pre>

When I remove the argument I get that error: 
<pre>ViewController.swift:25:41: Missing argument for parameter 'fromSVGFileNamed' in call</pre>

And then, trying with the suggested <code>fromSVGFileNamed</code> argument name, I get that error:
<pre>ViewController.swift:25:32: Cannot invoke 'init' with an argument list of type '(fromSVGFileNamed: StringLiteralConvertible)'</pre>
Am I missing something here?

**Comment by arielelkin** [comment]
That's because you're assuming that `pathFromSVGFileNamed` is a [class factory method](https://developer.apple.com/library/ios/documentation/General/Conceptual/CocoaEncyclopedia/ClassFactoryMethods/ClassFactoryMethods.html), such as:
`UIColor *color = [UIColor colorWithRed:0.5 green:0.0 blue:0.5 alpha:1.0];`

Factory methods do get mapped as convenience initializers in Swift:
`let color = UIColor(red: 0.5, green: 0.0, blue: 0.5, alpha: 1.0)`

But `pathFromSVGFileNamed` is not a factory method, it's a regular class method. As such, you use it like this:
`let myPath = PocketSVG.pathFromSVGFileNamed("BezierCurve1").takeUnretainedValue()`

See the **Initialization** section of the [Interacting with Objective-C APIs](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html) doc.

I've updated PocketSVG's documentation accordingly.
